# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe2ee44d706a1fa3f7bcd92c7e071d01319f86105b9de5f309cecdc345519fc1d8bc3078e03d430ce3b62cfd570a168af6ca9cf52c1309aa23d31bcd9d35c3e

test:
  secret_key_base: 583a09f4c2279f17194402bc3b73f4c13866d9318b361bb2e5d3e0453947b0b9f17082f85fdf9ede524d3b8d563d42db6db544ad72fac2a8c244d3347710af26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
